resource_group_name = "rg-chesscombocms"
storage_account_name = "chesscombocmsstorage"
static_storage_account_name = "cmsstatic"
env = "dev"
location = "westeurope"
chess_combo_connection_string = "Server=94.237.94.140;Port=5432;Database=chess-combo;User Id=brane;Password=branislav;Include Error Detail=true;"
app_service_plan_size = "F1"
app_service_plan_tier = "F1"