# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - chess-combo-cms-api

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - uses: azure/docker-login@v1
      with:
        login-server: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_555625eb63af47c48afc23216f9c717f }}
        password: ${{ secrets.AzureAppService_ContainerPassword_482ac3b05e14452fbc6df2c169905e2c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2.2.1
      with:
        push: true
        tags: milosponj/chess-combo-cms:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'chess-combo-cms-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_be698ecf4deb4e6fabbfb23fbb8c5b4c }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_555625eb63af47c48afc23216f9c717f }}/milosponj/chess-combo-cms:${{ github.sha }}'